---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache
    tags: always
    package:
      update_cache: yes
    changed_when: false

- hosts: all
  become: true
  roles:
    - base

- hosts: HA_proxys
  become: true
  roles:
    - HAproxys

- hosts: postgres_servers
  become: true
  roles:
    - postgres_servers

